export const SET_ME_NOTE_LIST = 'SET_ME_NOTE_LIST';
export const SET_ALL_NOTE_LIST = 'SET_ALL_NOTE_LIST';
export const SET_NOTE_DETAILS_LIST = 'SET_NOTE_DETAILS_LIST';
export const NEW_NOTE_LIST = 'NEW_NOTE_LIST';
export const SET_SELECT_COURSE_LIST = 'SET_SELECT_COURSE_LIST';
